[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "face-utils"
version = "0.1.0"
description = "Utilities for 3D face clustering, reconstruction, and registration"
authors = [{name = "Peter Zhang"}]
requires-python = ">=3.8"
